apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: traefik
  name: traefik
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
    spec:
      containers:
      - image: traefik:2.9.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 9000
          name: treafik
          protocol: TCP
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: websecure
          protocol: TCP
        - containerPort: 8082
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/traefik
          name: config
        - mountPath: /etc/traefik/file
          name: config-file
        - mountPath: /etc/traefik/cert
          name: cert
#        - mountPath: /etc/traefik/acme
#          name: acme
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: traefik-config
        name: config
      - configMap:
          defaultMode: 420
          name: file-config-traefik
          optional: true
        name: config-file
      - name: cert
        secret:
          defaultMode: 420
          optional: true
          secretName: default-cert
#      - name: acme
#        persistentVolumeClaim:
#          claimName: traefik-acme
#          optional: true
