---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3www
spec:
  selector:
    matchLabels:
      app: s3www
  template:
    metadata:
      labels:
        app: s3www
    spec:
      containers:
      - name: s3www
        image: y4m4/s3www:v0.7.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
