apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex-server
  name: dex-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dex-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dex-server
    spec:
      serviceAccountName: dex
      containers:
      - command:
        - dex
        - serve
        - /etc/dex/dex.yaml
        image: ghcr.io/dexidp/dex:v2.36.0
        imagePullPolicy: IfNotPresent
        name: dex
        ports:
        - containerPort: 5556
          protocol: TCP
        - containerPort: 5557
          protocol: TCP
        - containerPort: 5558
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/dex
          name: config
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        secret:
          secretName: dex-config
