---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: 3200
    name: tempo
  - port: 14268
    targetPort: 14268
    name: jaeger
  - port: 4317
    targetPort: 4317
    name: grpc
  - port: 4318
    targetPort: 4318
    name: http    